configuration:
  debug: false

  meta:
    processDescription: "Automated Pipeline"

  dependencies:
    - mvn://com.walmartlabs.concord.plugins.basic:smtp-tasks:1.31.1
    - mvn://com.walmartlabs.concord.plugins.kube:1.21.74
    - mvn://com.walmartlabs.concord.plugins.git:1.36.0
    - mvn://com.walmartlabs.concord.plugins:jenkins-task:1.46.0
    - mvn://org.codehaus.groovy:groovy-all:pom:2.5.2
    - mvn://org.python:jython-standalone:2.7.1

  arguments:
    concordHost: ""
    defaultGitBaseUrl: ""
    doThrow: false
    githubBaseUrl: ""
    gitState:
      statuses:
        success: "success"
        failed: "failure"
        pending: "pending"
        error: "error"

  out:
    - status
    - pipelineExitCause
    - id

profiles:
  gitTrigger:
    configuration:
      arguments:
        triggerType: github

triggers:
  - github:
      version: 2
      entryPoint: "onPush"
      useInitiator: true
      activeProfiles: [gitTrigger]
      conditions:
        type: "push"
        githubOrg: "Neoworkz"
        githubRepo: ".*"
        branch: ".*"

  - github:
      version: 2
      entryPoint: "onPullRequest"
      useInitiator: true
      activeProfiles: [ gitTrigger ]
      conditions:
        type: "pull_request"
        githubOrg: "Neoworkz"
        githubRepo: ".*"
        branch: ".*"
        payload:
          action: [ "opened", "reopened", "synchronize" ]

flows:
  default:
    - log: '${initiator.username} started the flow.'

  assertOrganization:
    - if: ${projectInfo.orgName != 'neoworkz'}
      then:
        - throw: "Workflow is not allowed outside of the 'neoworkz' organization"

  onPush:
    - call: assertOrganization
    - log: >-
        ${event.sender} pushed ${event.commitId} to
        ${event.payload.organization.login/${event.payload.repository.name}

  onPullRequest:
    - call: assertOrganization
    - log: >-
        ${event.sender} modified pull request with commit ${event.commitId} and status ${event.status}
        on ${event.payload.organization.login}/${event.payload.repository.name}
